services:
  mysql:
    image: mysql:lts
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql

  php_fpm:
    build: ./backend
    ports:
      - 9000:9000
    volumes:
      - ./backend:/var/www/html
      - composer_data:/var/www/vendor
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./frontend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  mysql_data:
  composer_data: